from tkinter import *
from PIL import Image,ImageTk
import tkinter.messagebox as tmsg

def hospital(name):
    class image:
        def __init__(self, master,file,x,y,w,h):
            canvas =Canvas(master,width=300,height=200)
            canvas.pack(fill=X,pady=50)
            self.img= (Image.open(file))
            self.resized_image= self.img.resize((w,h),Image.LANCZOS)
            self.new_image= ImageTk.PhotoImage(self.resized_image,master=canvas,width=300,height=200) # Changes here
            canvas.create_image(x, y, image=self.new_image) # Changes here
    def rootW():
        main.destroy()
        root.deiconify()
        username.set("")
        password.set("")
    def singup2():   
        def back2():
            sing.destroy()
            main.deiconify()

        def update_db2():
        
        # global users,passs
            user = userEntry.get()
            user = user.upper()
            print(user)
            entry = f"\n{user}:{passEntry.get()}"
            with open("DB.txt","a") as f:
                f.write(entry)
            tmsg.showinfo("MY Hospital","Your Account is Succesfully Created")
            sing.destroy()
            root.deiconify()
        main.withdraw()
        sing=Tk()
        sing.geometry("600x600")
        sing.title("Registration Form - My Hospital")
        sing.wm_iconbitmap("1.ico")
        sing.config(bg="black")
        back = Button(sing,text="<<Bact to Main Page",font="lucida 10 underline",fg="blue",bg="black",border=0,command=back2)
        back.pack(anchor=E)
        text1 = Label(sing,text="Register",fg="white",bg="black",font="Fixedsys 20 bold")
        text1.pack()
        text2 = Label(sing,text="Create Your own Account in My Hospital",fg="white",bg="black",font="Fixedsys 5")
        text2.pack()
        f = Frame(sing,bg="black",padx=60)
        f.pack(anchor=W)
        f1 = Frame(sing,bg="black",padx=60)
        f1.pack(anchor=W)
        f2 = Frame(sing,bg="black",padx=60)
        f2.pack(anchor=W)
        f3 = Frame(sing,bg="black",padx=60)
        f3.pack(anchor=W)
        f4 = Frame(sing,bg="black",padx=60)
        f4.pack(anchor=W)
        f5 = Frame(sing,bg="black",padx=60)
        f5.pack(anchor=W)
        name= Label(f,text="Name:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
        name.pack(anchor=W,padx=50,pady=5,side=LEFT)
        nameEntry = Entry(f)
        nameEntry.pack(side=LEFT,padx=25)
        age= Label(f1,text="age:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
        age.pack(anchor=W,padx=50,pady=5,side=LEFT)
        ageEntry = Entry(f1)
        ageEntry.pack(side=LEFT,padx=40)
        father= Label(f2,text="father name:- ",fg="grey",bg="black",padx=20,pady=10,relief=SUNKEN)
        father.pack(anchor=W,padx=50,pady=5,side=LEFT)
        fatherEntry = Entry(f2)
        fatherEntry.pack(side=LEFT)
        email= Label(f3,text="Email:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
        email.pack(anchor=W,padx=50,pady=5,side=LEFT)
        emailEntry = Entry(f3)
        emailEntry.pack(side=LEFT,padx=30)
        username1= Label(f4,text="username:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
        username1.pack(anchor=W,padx=50,pady=5,side=LEFT)
        userEntry = Entry(f4)
        userEntry.pack(side=LEFT)
        password1= Label(f5,text="password:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
        password1.pack(anchor=W,padx=50,pady=5,side=LEFT)
        passEntry = Entry(f5)
        passEntry.pack(side=LEFT)
        singupButton = Button(sing,text="Sing-Up",font="Impact 10",padx=20,pady=10,command=update_db2)
        singupButton.pack(pady=30)
        sing.mainloop()
    root.withdraw()
    main = Tk()
    width = main.winfo_screenwidth()
    hieght = main.winfo_screenheight()
    main.geometry(f"{width}x{hieght}")
    f = Frame(main,bg="black")
    f.pack(fill=X)
    home = Button(f,text="Home",font="Perpetua 12 underline",fg="white",bg="black",padx=10,border=0)
    home.pack(side=LEFT)
    about = Button(f,text="About us",font="Perpetua 12 underline",fg="white",bg="black",padx=10,border=0)
    about.pack(side=LEFT)
    contact = Button(f,text="Contact",font="Perpetua 12 underline",fg="white",bg="black",padx=10,border=0)
    contact.pack(side=LEFT)
    help = Button(f,text="Help",font="Perpetua 12 underline",fg="white",bg="black",padx=10,border=0)
    help.pack(side=LEFT)
    Login = Button(f,text="Login",font="Perpetua 12 underline",fg="white",bg="black",padx=10,border=0,command=rootW)
    Login.pack(side=LEFT)
    sing1 = Button(f,text="Sing up",font="Perpetua 12 underline",fg="white",bg="black",padx=10,border=0,command=singup2)
    sing1.pack(side=LEFT)
    search = Entry(f,font="lucida")
    search.pack(side=RIGHT,padx=15)
    main.title(f"My Hospital - {name}")
    text1 = Label(main,text=f'Welcome Back!! \n "{name}" to My Hospital"',font="Harrington 20 bold",fg="black")
    text1.pack()
    text2 = Label(main,text="Our Hospital is the only one in our country \n you can't find this like hospital in history of India Hope you like our service which is provide by us \n The owner of this Hospital is MD RUSHAAN ANSARI ")
    text2.pack()
    canvas = Canvas(main)
    canvas.pack()
    canvas.create_rectangle(190,0,160,160,fill="red")
    canvas.create_rectangle(100,60,250,95,fill="red",outline="red")
    f4 = Frame(main)
    f4.pack()
    text4 = Label(f4,text="Purchase Your Medine",fg="grey",bg="black",padx=80,pady=10,font="lucida 10")
    text4.pack(side=LEFT,padx=5)
    text5 = Label(f4,text="Donate Your Blood",fg="grey",bg="black",padx=80,pady=10,font="lucida 10")
    text5.pack(side=LEFT,padx=5)
    text6 = Label(f4,text="Fixed Meeting",fg="grey",bg="black",padx=80,pady=10,font="lucida 10")
    text6.pack(side=LEFT,padx=5)
    text7 = Label(f4,text="Apply Job",fg="grey",bg="black",padx=80,pady=10,font="lucida 10")
    text7.pack(side=LEFT,padx=5)
    image1 = image(main,'5.jpg',700,0,800,500)
    # scroll = Scrollbar(main,orient=HORIZONTAL)
    # scroll.pack(fill=Y)
    # main.config(yscrollcommand=scroll.set)
    # scroll.config(command=main.yview)
    main.mainloop()
def login():
    with open("DB.txt","r") as f:
        temp = f.read()
        temp = temp.split("\n")
    user = username.get()
    user = user.upper()
    name = f"{user}:{password.get()}"
    if name in temp:
        hospital(user)
    else:
        tmsg.showinfo("My Hospital","your username or password is incorrect")

    

def singup():   
    def back():
        sing.destroy()
        root.deiconify()

    def update_db():
    
    # global users,passs
        user = userEntry.get()
        user = user.upper()
        print(user)
        entry = f"\n{user}:{passEntry.get()}"
        with open("DB.txt","a") as f:
            f.write(entry)
        tmsg.showinfo("MY Hospital","Your Account is Succesfully Created")
        sing.destroy()
        root.deiconify()
    root.withdraw()
    sing=Tk()
    sing.geometry("600x600")
    sing.title("Registration Form - My Hospital")
    sing.wm_iconbitmap("1.ico")
    sing.config(bg="black")
    back = Button(sing,text="<<Bact to Login Page",font="lucida 10 underline",fg="blue",bg="black",border=0,command=back)
    back.pack(anchor=E)
    text1 = Label(sing,text="Register",fg="white",bg="black",font="Fixedsys 20 bold")
    text1.pack()
    text2 = Label(sing,text="Create Your own Account in My Hospital",fg="white",bg="black",font="Fixedsys 5")
    text2.pack()
    f = Frame(sing,bg="black",padx=60)
    f.pack(anchor=W)
    f1 = Frame(sing,bg="black",padx=60)
    f1.pack(anchor=W)
    f2 = Frame(sing,bg="black",padx=60)
    f2.pack(anchor=W)
    f3 = Frame(sing,bg="black",padx=60)
    f3.pack(anchor=W)
    f4 = Frame(sing,bg="black",padx=60)
    f4.pack(anchor=W)
    f5 = Frame(sing,bg="black",padx=60)
    f5.pack(anchor=W)
    name= Label(f,text="Name:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
    name.pack(anchor=W,padx=50,pady=5,side=LEFT)
    nameEntry = Entry(f)
    nameEntry.pack(side=LEFT,padx=25)
    age= Label(f1,text="age:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
    age.pack(anchor=W,padx=50,pady=5,side=LEFT)
    ageEntry = Entry(f1)
    ageEntry.pack(side=LEFT,padx=40)
    father= Label(f2,text="father name:- ",fg="white",bg="black",padx=20,pady=10,relief=SUNKEN)
    father.pack(anchor=W,padx=50,pady=5,side=LEFT)
    fatherEntry = Entry(f2)
    fatherEntry.pack(side=LEFT)
    email= Label(f3,text="Email:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
    email.pack(anchor=W,padx=50,pady=5,side=LEFT)
    emailEntry = Entry(f3)
    emailEntry.pack(side=LEFT,padx=30)
    username1= Label(f4,text="username:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
    username1.pack(anchor=W,padx=50,pady=5,side=LEFT)
    userEntry = Entry(f4)
    userEntry.pack(side=LEFT)
    password1= Label(f5,text="password:- ",fg="white",bg="black",relief=SUNKEN,pady=10,padx=10)
    password1.pack(anchor=W,padx=50,pady=5,side=LEFT)
    passEntry = Entry(f5)
    passEntry.pack(side=LEFT)
    singupButton = Button(sing,text="Sing-Up",font="Impact 10",padx=20,pady=10,command=update_db)
    singupButton.pack(pady=30)
    sing.mainloop()
root=Tk()
root.geometry("600x600")
root.title("My Hospital")
root.config(bg="black")
root.wm_iconbitmap("1.ico")
singup = Button(root,text="If You Want To Register:- Sign-up",font="lucida 10 underline",fg="blue",bg="black",border=0,command=singup)
singup.pack(anchor=E)

text1 = Label(root,text="Welcome To My Hospital",font="Fixedsys 20 bold",bg="black",fg="white")
text1.pack()
text2 = Label(root,text="contact:- 9136xxxxxxx",font="lucida 10",bg="black",fg="white")
text2.pack()
text3 = Label(root,text="**This is my login page**",bg="black",fg="white")
text3.pack()

username = StringVar()
password = StringVar()
f = Frame(root,bg="black",padx=60,pady=20)
f.pack(anchor=W)
f1 = Frame(root,bg="black")
f1.pack(anchor=W)
usernameText = Label(f,text="Username:- ",bg="black",fg="white",font="Terminal 25",pady=40,padx=20)
usernameText.pack(side=LEFT)
userenter = Entry(f,textvariable=username)
userenter.pack(side=LEFT)
usernameText = Label(f1,text="Password:- ",bg="black",fg="white",font="Terminal 25",padx=50,pady=20)
usernameText.pack(side=LEFT)
passenter = Entry(f1,textvariable=password,show="*")
passenter.pack(side=LEFT)
submitButton = Button(root,text="Login",font="Impact 10",padx=20,pady=10,command=login)
submitButton.pack(pady=30)


root.mainloop()
